Repository GPflow/GPflow, pull requests merged in 2018-06, with the labels that each got.

#724 Multi-output conditionals
  .coveragerc
  .travis.yml
  doc/source/notebooks/multiclass.ipynb
  doc/source/notebooks/multioutput.ipynb
  doc/source/notebooks/new_multioutput_gp_features.png
  doc/source/notebooks/new_multioutput_gp_kernels.png
  gpflow/__init__.py
  gpflow/conditionals.py
  gpflow/dispatch.py
  gpflow/expectations.py
  gpflow/features.py
  gpflow/gpflowrc
  gpflow/kullback_leiblers.py
  gpflow/logdensities.py
  gpflow/models/gpr.py
  gpflow/models/model.py
  gpflow/models/sgpmc.py
  gpflow/models/sgpr.py
  gpflow/models/svgp.py
  gpflow/multioutput/__init__.py
  gpflow/multioutput/conditionals.py
  gpflow/multioutput/features.py
  gpflow/multioutput/kernels.py
  gpflow/session_manager.py
  gpflow/test_util.py
  tests/test_config.py
  tests/test_coregion.py
  tests/test_hmc.py
  tests/test_method_equivalence.py
  tests/test_multioutput.py
  tests/test_multioutput_features.py
  tests/test_notebooks.py
  tests/test_predict.py
  tests/test_uncertain_conditional.py
Labels: enhancement, feature, in review

#789 Speed up notebooks
  doc/source/notebooks/FITCvsVFE.ipynb
  doc/source/notebooks/FITCvsVFE.py
  doc/source/notebooks/GPLVM.ipynb
  doc/source/notebooks/SGPR_notes.ipynb
  doc/source/notebooks/Sanity_check.ipynb
  doc/source/notebooks/classification.ipynb
  doc/source/notebooks/coreg_demo.ipynb
  doc/source/notebooks/data/three_phase_oil_flow.npz
  doc/source/notebooks/kernels.ipynb
  doc/source/notebooks/mcmc.ipynb
  doc/source/notebooks/models.ipynb
  doc/source/notebooks/monitor-tensorboard.ipynb
  doc/source/notebooks/multiclass.ipynb
  doc/source/notebooks/multioutput.ipynb
  doc/source/notebooks/natural_gradients.ipynb
  doc/source/notebooks/ordinal.ipynb
  doc/source/notebooks/regression.ipynb
  doc/source/notebooks/settings.ipynb
  doc/source/notebooks/svi_test.ipynb
  doc/source/notebooks/upper_bound.ipynb
  doc/source/notebooks/vgp_notes.ipynb
  gpflow/__init__.py
  gpflow/models/model.py
  gpflow/session_manager.py
  gpflow/test_util.py
  tests/test_hmc.py
  tests/test_notebooks.py
Labels: please review and merge

#768 removed jitter in nat grads
  gpflow/training/natgrad_optimizer.py
  tests/test_optimizers.py
Labels: bugfix

#712 Notebook to demonstrate advanced usage such as combining GP with Neural Network
  doc/source/notebooks/advanced_usage.ipynb
  doc/source/notebooks/natural_gradients.ipynb
  tests/test_notebooks.py
Labels: please review and merge

#704 changed Minibatch class so that it can change the shape of data freely
  gpflow/params/dataholders.py
  tests/test_dataholders.py
Labels: not ready for merge

#799 Monte-Carlo likelihoods
  RELEASE.md
  gpflow/likelihoods.py
  gpflow/logdensities.py
  gpflow/quadrature.py
  tests/test_dataholders.py
  tests/test_likelihoods.py
  tests/test_variational.py
Labels: help wanted, please review and merge
