Repository GPflow/GPflow, pull requests merged in 2019-10, with the labels that each got.

#1063 Rename inducing_variables -> inducing_variable as model attribute
  gpflow/kullback_leiblers.py
  gpflow/models/gplvm.py
  gpflow/models/sgpmc.py
  gpflow/models/sgpr.py
  gpflow/models/svgp.py
  gpflow/models/util.py
  notebooks2/advanced/convolutional.ipynb
  notebooks2/advanced/multioutput.ipynb
  notebooks2/basics/gplvm.ipynb
  notebooks2/intro_to_gpflow2.ipynb
  tests/test_features.py
  tests/test_gplvm.py
  tests/test_likelihoods.py
  tests/test_mean_functions.py
  tests/test_method_equivalence.py
  tests/test_methods.py
  tests/test_multioutput.py
  tests/test_multioutput_features.py
  tests/test_predict.py
  tests/test_printing.py
  tests/test_training.py
  tests/test_uncertain_conditional.py
  tests/test_variational.py
Labels: please review and merge

#1052 Periodic++
  .gitignore
  gpflow/kernels.py
  tests/reference.py
  tests/test_kerns.py
Labels: please review and merge

#1060 remove default argument to set_trainable (was False)
  gpflow/utilities/utilities.py
Labels: please review and merge

#1074 Clean up dependencies and setup instructions
  .circleci/config.yml
  .travis.yml
  README.md
  gpflow/ci_utils.py
  setup.py
  tests/test_gplvm.py
  tests_requirements.txt
Labels: please review and merge

#1096 Remove tf_graphs_and_sessions notebook
  doc/source/notebooks/intro.ipynb
  doc/source/notebooks/understanding/tf_graphs_and_sessions.ipynb
  tests/test_notebooks.py
Labels: please review and merge

#1076 GPflow2.0 notebook update: regression.ipynb
  doc/source/notebooks/basics/regression.ipynb
Labels: ready to merge

#1083 GPflow2: Fix behaviour of likelihood quadrature tests
  tests/test_likelihoods.py
Labels: bug, please review and merge

#1097 Quickfix: enable notebook test of regression.ipynb
  tests/test_notebooks.py
Labels: ready to merge

#1087 GPflow2.0 notebook update: kernel design
  doc/source/notebooks/tailor/kernel_design.ipynb
  tests/test_notebooks.py
Labels: please review and merge

#1092 Multiclass classification notebook 2.0
  doc/source/notebooks/advanced/multiclass_classification.ipynb
  doc/source/notebooks/advanced/multiclass_classification.py
  tests/test_notebooks.py
Labels: ready to merge

#1062 Notebook for Variational Fourier Features
  doc/source/notebooks/advanced/variational_fourier_features.ipynb
  doc/source/notebooks/intro.ipynb
  gpflow/base.py
  gpflow/covariances/kufs.py
  gpflow/covariances/kuus.py
  gpflow/models/model.py
  tests/test_model.py
Labels: please review and merge

#1104 GPflow 2.0 notebook update: FITC vs VFE
  doc/source/notebooks/theory/FITCvsVFE.ipynb
  doc/source/notebooks/theory/FITCvsVFE.py
  gpflow/optimizers/scipy.py
  tests/test_notebooks.py
Labels: help wanted
