Repository GPflow/GPflow, pull requests merged in 2020-03, with the labels that each got.

#1213 Fix more potential tf.cast() loss-of-precision issues
  doc/source/notebooks/advanced/variational_fourier_features.pct.py
  doc/source/notebooks/intro_to_gpflow2.pct.py
  doc/source/notebooks/tailor/gp_nn.pct.py
  gpflow/base.py
  gpflow/kernels/convolutional.py
  gpflow/kernels/misc.py
  gpflow/kullback_leiblers.py
  gpflow/likelihoods/likelihoods.py
  gpflow/likelihoods/robustmax.py
  gpflow/logdensities.py
  gpflow/models/gplvm.py
  gpflow/models/sgpr.py
  gpflow/quadrature.py
  gpflow/utilities/ops.py
  gpflow/utilities/utilities.py
  tests/gpflow/likelihoods/test_likelihoods.py
  tests/gpflow/models/test_sgpr.py
  tests/gpflow/optimizers/test_scipy.py
  tests/gpflow/test_logdensities.py
Labels: help wanted, please review and merge

#1219 assert_shapes in code instead of just comments
  gpflow/conditionals/mo_conditionals.py
  gpflow/conditionals/util.py
  gpflow/kullback_leiblers.py
  gpflow/logdensities.py
  tests/gpflow/conditionals/test_multioutput.py
Labels: please review and merge

#1334 improve shape robustness in likelihoods
  doc/source/notebooks/advanced/natural_gradients.pct.py
  doc/source/notebooks/advanced/ordinal_regression.pct.py
  doc/source/notebooks/advanced/varying_noise.pct.py
  gpflow/likelihoods/__init__.py
  gpflow/likelihoods/likelihoods.py
  gpflow/models/model.py
  gpflow/quadrature.py
  tests/gpflow/kernels/test_coregion.py
  tests/gpflow/likelihoods/test_likelihoods.py
  tests/gpflow/likelihoods/test_switched_likelihood.py
  tests/gpflow/models/test_methods.py
  tests/gpflow/models/test_model_predict.py
Labels: discussion, enhancement, please review and merge

#1344 Monitoring of optimisation
  doc/source/notebooks/basics/monitoring.pct.py
  doc/source/notebooks/intro_to_gpflow2.pct.py
  doc/source/notebooks/intro_to_gpflow2_plotting.py
  gpflow/__init__.py
  gpflow/monitor.py
  tests/gpflow/test_monitor.py
Labels: enhancement

#1384 minimum required multipledispatch version is 0.6
  setup.py
Labels: please review and merge

#1377 Make Scipy more robust & faster
  doc/source/notebooks/advanced/gps_for_big_data.pct.py
  doc/source/notebooks/intro_to_gpflow2.pct.py
  doc/source/notebooks/tailor/external-mean-function.pct.py
  doc/source/notebooks/tailor/mixture_density_network.pct.py
  gpflow/optimizers/natgrad.py
  gpflow/optimizers/scipy.py
  gpflow/utilities/utilities.py
  tests/gpflow/expectations/test_expectations.py
  tests/gpflow/kernels/test_scaled_euclid_dist.py
  tests/gpflow/models/test_svgp.py
Labels: please review and merge

#1370 fix notebook LaTeX equations + upgrade guide link
  doc/source/index.rst
  doc/source/notebooks/advanced/changepoints.pct.py
  doc/source/notebooks/advanced/coregionalisation.pct.py
  doc/source/notebooks/advanced/gps_for_big_data.pct.py
  doc/source/notebooks/advanced/mcmc.pct.py
  doc/source/notebooks/advanced/multiclass_classification.pct.py
  doc/source/notebooks/advanced/multioutput.pct.py
  doc/source/notebooks/advanced/ordinal_regression.pct.py
  doc/source/notebooks/advanced/variational_fourier_features.pct.py
  doc/source/notebooks/advanced/varying_noise.pct.py
  doc/source/notebooks/basics/regression.pct.py
  doc/source/notebooks/gpflow2_upgrade_guide.md
  doc/source/notebooks/tailor/kernel_design.pct.py
  doc/source/notebooks/tailor/mixture_density_network.pct.py
  doc/source/notebooks/theory/SGPR_notes.md
  doc/source/notebooks/theory/upper_bound.pct.py
  doc/source/notebooks/theory/vgp_notes.md
Labels: please review and merge

#1374 MCMC cleanup
  doc/source/notebooks/advanced/mcmc.pct.py
  doc/source/notebooks/advanced/multiclass_classification.py
  gpflow/optimizers/mcmc.py
  tests/gpflow/optimizers/test_mcmc.py
  tests/gpflow/test_monitor.py
Labels: please review and merge

#1338 enable pickling of frozen models
  gpflow/utilities/utilities.py
  tests/gpflow/utilities/test_deepcopy.py
Labels: please review and merge

#1389 Added suggestion on how to open TensorBoard so it updates.
  doc/source/notebooks/basics/monitoring.pct.py
Labels: please review and merge

#1388 Increased tolerance for sqrt in kernels K_r2.
  gpflow/kernels/stationaries.py
Labels: please review and merge

#1391 Improve doc generation
  .circleci/config.yml
  doc/README.md
  doc/source/generate_module_rst.py
  gpflow/ci_utils.py
  setup.py
Labels: please review and merge

#1393 _scalar_log_density -> _scalar_log_prob
  gpflow/likelihoods/likelihoods.py
Labels: please review and merge
