Repository GPflow/GPflow, pull requests merged in 2020-02, with the labels that each got.

#1242 quickfix kernel_design notebook
  doc/source/notebooks/tailor/kernel_design.ipynb
  doc/source/notebooks/tailor/kernel_design.pct.py
Labels: please review and merge

#1177 Defining priors with transforms
  doc/source/notebooks/advanced/mcmc.ipynb
  doc/source/notebooks/advanced/mcmc.pct.py
  gpflow/base.py
  gpflow/optimizers/mcmc.py
  tests/test_mcmc_helper.py
  tests/test_prior.py
Labels: discussion

#1223 Inconisistency on whether q_sqrt is triangular fixed.
  gpflow/conditionals/util.py
  tests/test_conditionals.py
  tests/test_kldiv.py
Labels: bug

#1231 Improve documentation and behaviour of Periodic kernel
  doc/source/notebooks/gpflow_2_upgrade/gpflow2_upgrade_guide.ipynb
  gpflow/kernels/base.py
  gpflow/kernels/periodic.py
  gpflow/kernels/stationaries.py
  gpflow/utilities/ops.py
  tests/test_kernels.py
Labels: please review and merge

#1285 preserve types in deepcopy
  gpflow/utilities/utilities.py
Labels: bugfix
